//
//  Font header: eui_test_font
//  Auto-generated by ESGUI Font Generator v1.2.0 (二分查找优化版)
//

#ifndef eui_test_font_H
#define eui_test_font_H

#include "ESGUI_Def.h"
#include "ESGUI_BSP_Text.h"

extern const Font eui_test_font;

#endif /* eui_test_font_H */
