//
//  Font data: eui_test_font
//  Auto-generated by ESGUI Font Generator v1.0.0
//
//  Params:
//    Size:   12 px
//    Threshold: 128
//    Line height: 12 px
//    Base line:   8 px
//    Glyphs: 87
//

#include "eui_test_font.h"
#define NULL ((void*)0)

/* Bitmap blob (1123 bytes) */
static const uint8_t eui_test_font_bitmap[] = {
    0x02, 0x02, 0x02, 0x02, 0x02, 0x00, 0x7C, 0x82, 0x83, 0x83, 0x7C, 0x00, 0x00, 0x00, 0x00, 0x00, 
    0x00, 0x00, 0x08, 0x04, 0xFE, 0x00, 0x00, 0x00, 0x00, 0x00, 0xC4, 0xA2, 0x93, 0x93, 0x8C, 0x00, 
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x43, 0x93, 0x9B, 0x97, 0x63, 0x00, 0x00, 0x00, 0x00, 0x00, 
    0x00, 0x00, 0x38, 0x24, 0x22, 0xFF, 0x20, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x4F, 0x8B, 
    0x8B, 0x8B, 0x73, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x7C, 0x8A, 0x8B, 0x8B, 0x70, 0x00, 
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0xC3, 0x33, 0x0B, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 
    0x00, 0x00, 0x6C, 0x92, 0x93, 0x93, 0x6C, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x1C, 0xA2, 
    0xA3, 0xA3, 0x7C, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xE0, 0x38, 0x26, 0x38, 0xE0, 0x00, 
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x93, 0x93, 0x93, 0x6C, 0x00, 0x00, 0x00, 0x00, 0x00, 
    0x00, 0x00, 0x7C, 0x82, 0x83, 0x83, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x83, 
    0x83, 0x83, 0x7C, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x93, 0x93, 0x93, 0x83, 0x00, 
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x13, 0x13, 0x13, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 
    0x00, 0x00, 0x7C, 0x82, 0x83, 0x93, 0xF0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x10, 
    0x10, 0x10, 0xFE, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFE, 0x00, 0x00, 0x00, 0x60, 0x80, 
    0x80, 0x80, 0x7E, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x10, 0x28, 0x44, 0x82, 0x00, 
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x80, 0x80, 0x80, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 
    0x00, 0x00, 0xFF, 0x06, 0x08, 0x10, 0x08, 0x04, 0x06, 0xFE, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
    0x00, 0x00, 0xFF, 0x06, 0x08, 0x10, 0xFE, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x7C, 0x82, 
    0x83, 0x83, 0x7C, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x23, 0x23, 0x23, 0x1C, 0x00, 
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x7C, 0x82, 0x83, 0x83, 0x7C, 0x00, 0x00, 0x00, 0x00, 0x00, 
    0x01, 0x02, 0x02, 0x00, 0xFF, 0x13, 0x13, 0x13, 0xEC, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
    0x4C, 0x92, 0x93, 0x93, 0x60, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0x03, 0xFF, 0x03, 
    0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x7F, 0x80, 0x80, 0x80, 0x7E, 0x00, 0x00, 0x00, 
    0x00, 0x00, 0x00, 0x00, 0x0F, 0x30, 0xC0, 0x30, 0x0E, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
    0xFF, 0x80, 0x80, 0xFE, 0x80, 0x80, 0x80, 0x7E, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
    0x83, 0x44, 0x38, 0x44, 0x82, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0F, 0x10, 0xE0, 0x10, 
    0x0E, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xC3, 0xA3, 0x93, 0x8B, 0x87, 0x00, 0x00, 0x00, 
    0x00, 0x00, 0x00, 0x00, 0x10, 0x2A, 0x2A, 0x2A, 0x3C, 0x00, 0xFF, 0x88, 0x88, 0x88, 0x70, 0x00, 
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x1C, 0x22, 0x22, 0x22, 0x24, 0x00, 0x70, 0x88, 0x88, 0x88, 
    0xFE, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x1C, 0x2A, 0x2A, 0x2A, 0x2C, 0x00, 0x10, 0x10, 
    0xFC, 0x12, 0x13, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x1C, 0xA2, 0xA2, 0xA2, 0x7E, 0x00, 
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x10, 0x08, 0x08, 0xF0, 0x00, 0x00, 0x00, 0x00, 0x00, 
    0x00, 0x00, 0xF1, 0x00, 0x01, 0x00, 0x00, 0x00, 0xF1, 0x00, 0x04, 0x04, 0x03, 0x00, 0xFF, 0x00, 
    0x20, 0x50, 0x88, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFE, 0x00, 0x00, 0x00, 0x3E, 0x02, 
    0x02, 0x3E, 0x02, 0x02, 0x02, 0x3C, 0x3E, 0x04, 0x02, 0x02, 0x3C, 0x00, 0x1C, 0x22, 0x22, 0x22, 
    0x1C, 0x00, 0xFE, 0x22, 0x22, 0x22, 0x1C, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x1C, 0x22, 
    0x22, 0x22, 0xFE, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3E, 0x04, 0x02, 0x02, 0x00, 0x24, 
    0x2A, 0x2A, 0x2A, 0x12, 0x00, 0x08, 0x08, 0x7E, 0x8C, 0x88, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
    0x00, 0x1E, 0x20, 0x20, 0x10, 0x3E, 0x00, 0x06, 0x18, 0x20, 0x18, 0x06, 0x00, 0x3E, 0x20, 0x20, 
    0x3E, 0x20, 0x20, 0x20, 0x1E, 0x22, 0x14, 0x08, 0x14, 0x22, 0x00, 0x1E, 0xA0, 0xA0, 0xA0, 0x7E, 
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x22, 0x32, 0x2A, 0x26, 0x22, 0x00, 0x04, 0x04, 0x04, 
    0x04, 0x04, 0x04, 0x04, 0x06, 0x06, 0x04, 0x80, 0x80, 0x83, 0x83, 0x83, 0x83, 0x83, 0x83, 0xC0, 
    0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10, 0xF8, 0x07, 0xE0, 0x00, 
    0xF9, 0xFF, 0xAF, 0xA9, 0xF9, 0x00, 0x03, 0x00, 0x03, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x61, 
    0x11, 0x2F, 0x4F, 0xF9, 0x01, 0x00, 0xFC, 0x00, 0xFF, 0x00, 0x02, 0x02, 0x01, 0x00, 0x00, 0x00, 
    0x00, 0x02, 0x03, 0xFF, 0x93, 0x49, 0xBF, 0x7F, 0x29, 0x29, 0x49, 0x83, 0xFF, 0x03, 0x02, 0x02, 
    0x02, 0x03, 0x02, 0x02, 0x02, 0x02, 0x03, 0x10, 0xC8, 0x07, 0x06, 0xF6, 0x06, 0x06, 0x06, 0x56, 
    0x8C, 0x01, 0x00, 0x00, 0x02, 0x03, 0x00, 0x00, 0x00, 0x00, 0x01, 0x46, 0x26, 0xF6, 0x1E, 0x1E, 
    0xF6, 0xF6, 0x16, 0x16, 0xF0, 0x00, 0x00, 0x01, 0x00, 0x00, 0x03, 0x03, 0x00, 0x01, 0x01, 0x79, 
    0x49, 0xCF, 0x00, 0x7C, 0x7E, 0x7E, 0xFE, 0x5E, 0x7C, 0x02, 0x02, 0x01, 0x00, 0x01, 0x01, 0x03, 
    0x03, 0x01, 0x01, 0x21, 0xFF, 0x23, 0xFF, 0x33, 0x21, 0x20, 0x40, 0x22, 0x91, 0x03, 0x00, 0x00, 
    0x03, 0x00, 0x00, 0x00, 0x02, 0x01, 0x00, 0x00, 0x7C, 0x56, 0x56, 0x56, 0xD6, 0xD6, 0x5E, 0x7C, 
    0x00, 0x02, 0x01, 0x00, 0x03, 0x02, 0x02, 0x02, 0x02, 0x01, 0x02, 0x06, 0x06, 0x36, 0x46, 0x86, 
    0x66, 0x26, 0x0E, 0x06, 0x00, 0x02, 0x02, 0x01, 0x01, 0x00, 0x01, 0x01, 0x01, 0x02, 0x02, 0x86, 
    0x46, 0xA6, 0x96, 0xFE, 0xDE, 0x96, 0xA6, 0x46, 0x80, 0x00, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 
    0x00, 0x00, 0x00, 0x11, 0x22, 0x00, 0x7E, 0x03, 0xE1, 0xF3, 0x7E, 0x00, 0xFF, 0x02, 0x01, 0x00, 
    0x02, 0x01, 0x00, 0x00, 0x03, 0x00, 0x03, 0x11, 0x22, 0x00, 0xE0, 0xA0, 0xA0, 0xB0, 0xBE, 0xA0, 
    0xE0, 0x02, 0x01, 0x00, 0x03, 0x00, 0x00, 0x00, 0x00, 0x02, 0x03, 0x11, 0x22, 0x0E, 0xF6, 0x56, 
    0xFE, 0xFE, 0x56, 0xF6, 0x0C, 0x03, 0x00, 0x02, 0x02, 0x01, 0x01, 0x01, 0x01, 0x03, 0x02, 0xFE, 
    0x96, 0x96, 0xFE, 0x9E, 0x96, 0x96, 0x9E, 0xFC, 0x00, 0x00, 0x00, 0x00, 0x03, 0x02, 0x02, 0x02, 
    0x02, 0x02, 0x03, 0x10, 0x91, 0x11, 0x11, 0xF1, 0x11, 0x11, 0x11, 0x90, 0x10, 0x01, 0x00, 0x00, 
    0x02, 0x03, 0x00, 0x00, 0x00, 0x00, 0x01, 0xEE, 0xA6, 0xB6, 0x6E, 0xA6, 0xBE, 0xBE, 0x66, 0x26, 
    0xEC, 0x03, 0x02, 0x02, 0x02, 0x03, 0x02, 0x02, 0x03, 0x02, 0x03, 0x46, 0x56, 0xD6, 0x56, 0xFE, 
    0x7E, 0x56, 0x56, 0xD6, 0x40, 0x01, 0x03, 0x02, 0x02, 0x00, 0x01, 0x01, 0x01, 0x02, 0x02, 0x11, 
    0xF2, 0x00, 0x20, 0xE8, 0x28, 0x3C, 0x3E, 0xCC, 0x0F, 0x00, 0x03, 0x01, 0x02, 0x03, 0x02, 0x00, 
    0x00, 0x01, 0x02, 0x20, 0x20, 0xFF, 0x20, 0x60, 0xA4, 0xA2, 0x20, 0x20, 0x20, 0x00, 0x02, 0x03, 
    0x02, 0x02, 0x00, 0x00, 0x01, 0x02, 0x02, 0xF1, 0x02, 0x80, 0x40, 0x39, 0x01, 0x41, 0x81, 0x03, 
    0xFF, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x03, 0xF9, 0x09, 0xF9, 0xA9, 0xAF, 
    0xAF, 0xF9, 0xF9, 0x09, 0xF9, 0x03, 0x02, 0x03, 0x02, 0x02, 0x02, 0x02, 0x03, 0x02, 0x03, 0x01, 
    0xF9, 0x09, 0x09, 0xEF, 0x0F, 0x09, 0x09, 0xF9, 0x01, 0x02, 0x02, 0x02, 0x01, 0x00, 0x01, 0x01, 
    0x01, 0x02, 0x02, 
};

/* Glyph descriptors (87 glyphs) */
static const FontGlyph eui_test_font_glyphs[] = {
    /* [  0] U+002D '-' */
    {
        .bitmap_index = 0,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -4,
        .box_w       = 6,
        .box_h       = 2,
    },
    /* [  1] U+0030 '0' */
    {
        .bitmap_index = 6,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [  2] U+0031 '1' */
    {
        .bitmap_index = 18,
        .adv_w       = 7,
        .ofs_x       = 1,
        .ofs_y       = -7,
        .box_w       = 4,
        .box_h       = 9,
    },
    /* [  3] U+0032 '2' */
    {
        .bitmap_index = 26,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [  4] U+0033 '3' */
    {
        .bitmap_index = 38,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [  5] U+0034 '4' */
    {
        .bitmap_index = 50,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [  6] U+0035 '5' */
    {
        .bitmap_index = 62,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [  7] U+0036 '6' */
    {
        .bitmap_index = 74,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [  8] U+0037 '7' */
    {
        .bitmap_index = 86,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [  9] U+0038 '8' */
    {
        .bitmap_index = 98,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 10] U+0039 '9' */
    {
        .bitmap_index = 110,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 11] U+0041 'A' */
    {
        .bitmap_index = 122,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 12] U+0042 'B' */
    {
        .bitmap_index = 134,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 13] U+0043 'C' */
    {
        .bitmap_index = 146,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 14] U+0044 'D' */
    {
        .bitmap_index = 158,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 15] U+0045 'E' */
    {
        .bitmap_index = 170,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 16] U+0046 'F' */
    {
        .bitmap_index = 182,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 17] U+0047 'G' */
    {
        .bitmap_index = 194,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 18] U+0048 'H' */
    {
        .bitmap_index = 206,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 19] U+0049 'I' */
    {
        .bitmap_index = 218,
        .adv_w       = 4,
        .ofs_x       = 1,
        .ofs_y       = -7,
        .box_w       = 2,
        .box_h       = 9,
    },
    /* [ 20] U+004A 'J' */
    {
        .bitmap_index = 222,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 21] U+004B 'K' */
    {
        .bitmap_index = 234,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 22] U+004C 'L' */
    {
        .bitmap_index = 246,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 23] U+004D 'M' */
    {
        .bitmap_index = 258,
        .adv_w       = 9,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 8,
        .box_h       = 9,
    },
    /* [ 24] U+004E 'N' */
    {
        .bitmap_index = 274,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 25] U+004F 'O' */
    {
        .bitmap_index = 286,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 26] U+0050 'P' */
    {
        .bitmap_index = 298,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 27] U+0051 'Q' */
    {
        .bitmap_index = 310,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 7,
        .box_h       = 11,
    },
    /* [ 28] U+0052 'R' */
    {
        .bitmap_index = 324,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 29] U+0053 'S' */
    {
        .bitmap_index = 336,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 30] U+0054 'T' */
    {
        .bitmap_index = 348,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 31] U+0055 'U' */
    {
        .bitmap_index = 360,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 32] U+0056 'V' */
    {
        .bitmap_index = 372,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 33] U+0057 'W' */
    {
        .bitmap_index = 384,
        .adv_w       = 9,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 8,
        .box_h       = 9,
    },
    /* [ 34] U+0058 'X' */
    {
        .bitmap_index = 400,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 35] U+0059 'Y' */
    {
        .bitmap_index = 412,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 36] U+005A 'Z' */
    {
        .bitmap_index = 424,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 37] U+0061 'a' */
    {
        .bitmap_index = 436,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -5,
        .box_w       = 6,
        .box_h       = 7,
    },
    /* [ 38] U+0062 'b' */
    {
        .bitmap_index = 442,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 39] U+0063 'c' */
    {
        .bitmap_index = 454,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -5,
        .box_w       = 6,
        .box_h       = 7,
    },
    /* [ 40] U+0064 'd' */
    {
        .bitmap_index = 460,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 41] U+0065 'e' */
    {
        .bitmap_index = 472,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -5,
        .box_w       = 6,
        .box_h       = 7,
    },
    /* [ 42] U+0066 'f' */
    {
        .bitmap_index = 478,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 43] U+0067 'g' */
    {
        .bitmap_index = 490,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -5,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 44] U+0068 'h' */
    {
        .bitmap_index = 502,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 45] U+0069 'i' */
    {
        .bitmap_index = 514,
        .adv_w       = 4,
        .ofs_x       = 1,
        .ofs_y       = -8,
        .box_w       = 2,
        .box_h       = 10,
    },
    /* [ 46] U+006A 'j' */
    {
        .bitmap_index = 518,
        .adv_w       = 4,
        .ofs_x       = 0,
        .ofs_y       = -8,
        .box_w       = 4,
        .box_h       = 12,
    },
    /* [ 47] U+006B 'k' */
    {
        .bitmap_index = 526,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 48] U+006C 'l' */
    {
        .bitmap_index = 538,
        .adv_w       = 4,
        .ofs_x       = 1,
        .ofs_y       = -7,
        .box_w       = 2,
        .box_h       = 9,
    },
    /* [ 49] U+006D 'm' */
    {
        .bitmap_index = 542,
        .adv_w       = 9,
        .ofs_x       = 0,
        .ofs_y       = -5,
        .box_w       = 8,
        .box_h       = 7,
    },
    /* [ 50] U+006E 'n' */
    {
        .bitmap_index = 550,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -5,
        .box_w       = 6,
        .box_h       = 7,
    },
    /* [ 51] U+006F 'o' */
    {
        .bitmap_index = 556,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -5,
        .box_w       = 6,
        .box_h       = 7,
    },
    /* [ 52] U+0070 'p' */
    {
        .bitmap_index = 562,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -5,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 53] U+0071 'q' */
    {
        .bitmap_index = 574,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -5,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 54] U+0072 'r' */
    {
        .bitmap_index = 586,
        .adv_w       = 5,
        .ofs_x       = 0,
        .ofs_y       = -5,
        .box_w       = 5,
        .box_h       = 7,
    },
    /* [ 55] U+0073 's' */
    {
        .bitmap_index = 591,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -5,
        .box_w       = 6,
        .box_h       = 7,
    },
    /* [ 56] U+0074 't' */
    {
        .bitmap_index = 597,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 57] U+0075 'u' */
    {
        .bitmap_index = 609,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -5,
        .box_w       = 6,
        .box_h       = 7,
    },
    /* [ 58] U+0076 'v' */
    {
        .bitmap_index = 615,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -5,
        .box_w       = 6,
        .box_h       = 7,
    },
    /* [ 59] U+0077 'w' */
    {
        .bitmap_index = 621,
        .adv_w       = 9,
        .ofs_x       = 0,
        .ofs_y       = -5,
        .box_w       = 8,
        .box_h       = 7,
    },
    /* [ 60] U+0078 'x' */
    {
        .bitmap_index = 629,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -5,
        .box_w       = 6,
        .box_h       = 7,
    },
    /* [ 61] U+0079 'y' */
    {
        .bitmap_index = 635,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -5,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 62] U+007A 'z' */
    {
        .bitmap_index = 647,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -5,
        .box_w       = 6,
        .box_h       = 7,
    },
    /* [ 63] U+4E00 ' ' */
    {
        .bitmap_index = 653,
        .adv_w       = 11,
        .ofs_x       = 0,
        .ofs_y       = -5,
        .box_w       = 10,
        .box_h       = 3,
    },
    /* [ 64] U+4E8C ' ' */
    {
        .bitmap_index = 663,
        .adv_w       = 11,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 10,
        .box_h       = 9,
    },
    /* [ 65] U+503C ' ' */
    {
        .bitmap_index = 683,
        .adv_w       = 11,
        .ofs_x       = 0,
        .ofs_y       = -8,
        .box_w       = 10,
        .box_h       = 11,
    },
    /* [ 66] U+5217 ' ' */
    {
        .bitmap_index = 703,
        .adv_w       = 11,
        .ofs_x       = 0,
        .ofs_y       = -8,
        .box_w       = 10,
        .box_h       = 11,
    },
    /* [ 67] U+56FE ' ' */
    {
        .bitmap_index = 723,
        .adv_w       = 11,
        .ofs_x       = 0,
        .ofs_y       = -8,
        .box_w       = 10,
        .box_h       = 11,
    },
    /* [ 68] U+5C14 ' ' */
    {
        .bitmap_index = 743,
        .adv_w       = 11,
        .ofs_x       = 0,
        .ofs_y       = -8,
        .box_w       = 10,
        .box_h       = 11,
    },
    /* [ 69] U+5E03 ' ' */
    {
        .bitmap_index = 763,
        .adv_w       = 11,
        .ofs_x       = 0,
        .ofs_y       = -8,
        .box_w       = 10,
        .box_h       = 11,
    },
    /* [ 70] U+5F39 ' ' */
    {
        .bitmap_index = 783,
        .adv_w       = 11,
        .ofs_x       = 0,
        .ofs_y       = -8,
        .box_w       = 10,
        .box_h       = 11,
    },
    /* [ 71] U+5F62 ' ' */
    {
        .bitmap_index = 803,
        .adv_w       = 11,
        .ofs_x       = 0,
        .ofs_y       = -8,
        .box_w       = 10,
        .box_h       = 11,
    },
    /* [ 72] U+606F ' ' */
    {
        .bitmap_index = 823,
        .adv_w       = 11,
        .ofs_x       = 0,
        .ofs_y       = -8,
        .box_w       = 10,
        .box_h       = 11,
    },
    /* [ 73] U+6587 ' ' */
    {
        .bitmap_index = 843,
        .adv_w       = 11,
        .ofs_x       = 0,
        .ofs_y       = -8,
        .box_w       = 10,
        .box_h       = 11,
    },
    /* [ 74] U+672C ' ' */
    {
        .bitmap_index = 863,
        .adv_w       = 11,
        .ofs_x       = 0,
        .ofs_y       = -8,
        .box_w       = 10,
        .box_h       = 11,
    },
    /* [ 75] U+6D4B ' ' */
    {
        .bitmap_index = 883,
        .adv_w       = 11,
        .ofs_x       = 0,
        .ofs_y       = -8,
        .box_w       = 10,
        .box_h       = 11,
    },
    /* [ 76] U+6D88 ' ' */
    {
        .bitmap_index = 903,
        .adv_w       = 11,
        .ofs_x       = 0,
        .ofs_y       = -8,
        .box_w       = 10,
        .box_h       = 11,
    },
    /* [ 77] U+6F14 ' ' */
    {
        .bitmap_index = 923,
        .adv_w       = 11,
        .ofs_x       = 0,
        .ofs_y       = -8,
        .box_w       = 10,
        .box_h       = 11,
    },
    /* [ 78] U+7535 ' ' */
    {
        .bitmap_index = 943,
        .adv_w       = 11,
        .ofs_x       = 0,
        .ofs_y       = -8,
        .box_w       = 10,
        .box_h       = 11,
    },
    /* [ 79] U+793A ' ' */
    {
        .bitmap_index = 963,
        .adv_w       = 11,
        .ofs_x       = 0,
        .ofs_y       = -8,
        .box_w       = 10,
        .box_h       = 11,
    },
    /* [ 80] U+7A97 ' ' */
    {
        .bitmap_index = 983,
        .adv_w       = 11,
        .ofs_x       = 0,
        .ofs_y       = -8,
        .box_w       = 10,
        .box_h       = 11,
    },
    /* [ 81] U+8868 ' ' */
    {
        .bitmap_index = 1003,
        .adv_w       = 11,
        .ofs_x       = 0,
        .ofs_y       = -8,
        .box_w       = 10,
        .box_h       = 11,
    },
    /* [ 82] U+8BD5 ' ' */
    {
        .bitmap_index = 1023,
        .adv_w       = 11,
        .ofs_x       = 0,
        .ofs_y       = -8,
        .box_w       = 10,
        .box_h       = 11,
    },
    /* [ 83] U+957F ' ' */
    {
        .bitmap_index = 1043,
        .adv_w       = 11,
        .ofs_x       = 0,
        .ofs_y       = -8,
        .box_w       = 10,
        .box_h       = 11,
    },
    /* [ 84] U+95EA ' ' */
    {
        .bitmap_index = 1063,
        .adv_w       = 11,
        .ofs_x       = 0,
        .ofs_y       = -8,
        .box_w       = 10,
        .box_h       = 11,
    },
    /* [ 85] U+9762 ' ' */
    {
        .bitmap_index = 1083,
        .adv_w       = 11,
        .ofs_x       = 0,
        .ofs_y       = -8,
        .box_w       = 10,
        .box_h       = 11,
    },
    /* [ 86] U+9875 ' ' */
    {
        .bitmap_index = 1103,
        .adv_w       = 11,
        .ofs_x       = 0,
        .ofs_y       = -8,
        .box_w       = 10,
        .box_h       = 11,
    },
};

/* Unicode sparse list (1 codepoints) */
static const uint16_t eui_test_font_unicode_list_0[] = {
    0x002D, 
};

/* Unicode sparse list (1 codepoints) */
static const uint16_t eui_test_font_unicode_list_63[] = {
    0x4E00, 
};

/* Unicode sparse list (1 codepoints) */
static const uint16_t eui_test_font_unicode_list_64[] = {
    0x4E8C, 
};

/* Unicode sparse list (1 codepoints) */
static const uint16_t eui_test_font_unicode_list_65[] = {
    0x503C, 
};

/* Unicode sparse list (1 codepoints) */
static const uint16_t eui_test_font_unicode_list_66[] = {
    0x5217, 
};

/* Unicode sparse list (1 codepoints) */
static const uint16_t eui_test_font_unicode_list_67[] = {
    0x56FE, 
};

/* Unicode sparse list (1 codepoints) */
static const uint16_t eui_test_font_unicode_list_68[] = {
    0x5C14, 
};

/* Unicode sparse list (1 codepoints) */
static const uint16_t eui_test_font_unicode_list_69[] = {
    0x5E03, 
};

/* Unicode sparse list (1 codepoints) */
static const uint16_t eui_test_font_unicode_list_70[] = {
    0x5F39, 
};

/* Unicode sparse list (1 codepoints) */
static const uint16_t eui_test_font_unicode_list_71[] = {
    0x5F62, 
};

/* Unicode sparse list (1 codepoints) */
static const uint16_t eui_test_font_unicode_list_72[] = {
    0x606F, 
};

/* Unicode sparse list (1 codepoints) */
static const uint16_t eui_test_font_unicode_list_73[] = {
    0x6587, 
};

/* Unicode sparse list (1 codepoints) */
static const uint16_t eui_test_font_unicode_list_74[] = {
    0x672C, 
};

/* Unicode sparse list (1 codepoints) */
static const uint16_t eui_test_font_unicode_list_75[] = {
    0x6D4B, 
};

/* Unicode sparse list (1 codepoints) */
static const uint16_t eui_test_font_unicode_list_76[] = {
    0x6D88, 
};

/* Unicode sparse list (1 codepoints) */
static const uint16_t eui_test_font_unicode_list_77[] = {
    0x6F14, 
};

/* Unicode sparse list (1 codepoints) */
static const uint16_t eui_test_font_unicode_list_78[] = {
    0x7535, 
};

/* Unicode sparse list (1 codepoints) */
static const uint16_t eui_test_font_unicode_list_79[] = {
    0x793A, 
};

/* Unicode sparse list (1 codepoints) */
static const uint16_t eui_test_font_unicode_list_80[] = {
    0x7A97, 
};

/* Unicode sparse list (1 codepoints) */
static const uint16_t eui_test_font_unicode_list_81[] = {
    0x8868, 
};

/* Unicode sparse list (1 codepoints) */
static const uint16_t eui_test_font_unicode_list_82[] = {
    0x8BD5, 
};

/* Unicode sparse list (1 codepoints) */
static const uint16_t eui_test_font_unicode_list_83[] = {
    0x957F, 
};

/* Unicode sparse list (1 codepoints) */
static const uint16_t eui_test_font_unicode_list_84[] = {
    0x95EA, 
};

/* Unicode sparse list (1 codepoints) */
static const uint16_t eui_test_font_unicode_list_85[] = {
    0x9762, 
};

/* Unicode sparse list (1 codepoints) */
static const uint16_t eui_test_font_unicode_list_86[] = {
    0x9875, 
};

/* Cmap tables (28 entries) */
static const FontCmap eui_test_font_cmaps[] = {
    {
        .range_start    = 0x0030,  /* U+0030 ~ U+0039 */
        .range_length   = 10,
        .glyph_id_start = 1,
        .unicode_list   = NULL,
        .list_length    = 0,
        .type           = 0,
    },
    {
        .range_start    = 0x0041,  /* U+0041 ~ U+005A */
        .range_length   = 26,
        .glyph_id_start = 11,
        .unicode_list   = NULL,
        .list_length    = 0,
        .type           = 0,
    },
    {
        .range_start    = 0x0061,  /* U+0061 ~ U+007A */
        .range_length   = 26,
        .glyph_id_start = 37,
        .unicode_list   = NULL,
        .list_length    = 0,
        .type           = 0,
    },
    {
        .range_start    = 0,
        .range_length   = 0,
        .glyph_id_start = 0,
        .unicode_list   = eui_test_font_unicode_list_0,
        .list_length    = 1,
        .type           = 1,
    },
    {
        .range_start    = 0,
        .range_length   = 0,
        .glyph_id_start = 63,
        .unicode_list   = eui_test_font_unicode_list_63,
        .list_length    = 1,
        .type           = 1,
    },
    {
        .range_start    = 0,
        .range_length   = 0,
        .glyph_id_start = 64,
        .unicode_list   = eui_test_font_unicode_list_64,
        .list_length    = 1,
        .type           = 1,
    },
    {
        .range_start    = 0,
        .range_length   = 0,
        .glyph_id_start = 65,
        .unicode_list   = eui_test_font_unicode_list_65,
        .list_length    = 1,
        .type           = 1,
    },
    {
        .range_start    = 0,
        .range_length   = 0,
        .glyph_id_start = 66,
        .unicode_list   = eui_test_font_unicode_list_66,
        .list_length    = 1,
        .type           = 1,
    },
    {
        .range_start    = 0,
        .range_length   = 0,
        .glyph_id_start = 67,
        .unicode_list   = eui_test_font_unicode_list_67,
        .list_length    = 1,
        .type           = 1,
    },
    {
        .range_start    = 0,
        .range_length   = 0,
        .glyph_id_start = 68,
        .unicode_list   = eui_test_font_unicode_list_68,
        .list_length    = 1,
        .type           = 1,
    },
    {
        .range_start    = 0,
        .range_length   = 0,
        .glyph_id_start = 69,
        .unicode_list   = eui_test_font_unicode_list_69,
        .list_length    = 1,
        .type           = 1,
    },
    {
        .range_start    = 0,
        .range_length   = 0,
        .glyph_id_start = 70,
        .unicode_list   = eui_test_font_unicode_list_70,
        .list_length    = 1,
        .type           = 1,
    },
    {
        .range_start    = 0,
        .range_length   = 0,
        .glyph_id_start = 71,
        .unicode_list   = eui_test_font_unicode_list_71,
        .list_length    = 1,
        .type           = 1,
    },
    {
        .range_start    = 0,
        .range_length   = 0,
        .glyph_id_start = 72,
        .unicode_list   = eui_test_font_unicode_list_72,
        .list_length    = 1,
        .type           = 1,
    },
    {
        .range_start    = 0,
        .range_length   = 0,
        .glyph_id_start = 73,
        .unicode_list   = eui_test_font_unicode_list_73,
        .list_length    = 1,
        .type           = 1,
    },
    {
        .range_start    = 0,
        .range_length   = 0,
        .glyph_id_start = 74,
        .unicode_list   = eui_test_font_unicode_list_74,
        .list_length    = 1,
        .type           = 1,
    },
    {
        .range_start    = 0,
        .range_length   = 0,
        .glyph_id_start = 75,
        .unicode_list   = eui_test_font_unicode_list_75,
        .list_length    = 1,
        .type           = 1,
    },
    {
        .range_start    = 0,
        .range_length   = 0,
        .glyph_id_start = 76,
        .unicode_list   = eui_test_font_unicode_list_76,
        .list_length    = 1,
        .type           = 1,
    },
    {
        .range_start    = 0,
        .range_length   = 0,
        .glyph_id_start = 77,
        .unicode_list   = eui_test_font_unicode_list_77,
        .list_length    = 1,
        .type           = 1,
    },
    {
        .range_start    = 0,
        .range_length   = 0,
        .glyph_id_start = 78,
        .unicode_list   = eui_test_font_unicode_list_78,
        .list_length    = 1,
        .type           = 1,
    },
    {
        .range_start    = 0,
        .range_length   = 0,
        .glyph_id_start = 79,
        .unicode_list   = eui_test_font_unicode_list_79,
        .list_length    = 1,
        .type           = 1,
    },
    {
        .range_start    = 0,
        .range_length   = 0,
        .glyph_id_start = 80,
        .unicode_list   = eui_test_font_unicode_list_80,
        .list_length    = 1,
        .type           = 1,
    },
    {
        .range_start    = 0,
        .range_length   = 0,
        .glyph_id_start = 81,
        .unicode_list   = eui_test_font_unicode_list_81,
        .list_length    = 1,
        .type           = 1,
    },
    {
        .range_start    = 0,
        .range_length   = 0,
        .glyph_id_start = 82,
        .unicode_list   = eui_test_font_unicode_list_82,
        .list_length    = 1,
        .type           = 1,
    },
    {
        .range_start    = 0,
        .range_length   = 0,
        .glyph_id_start = 83,
        .unicode_list   = eui_test_font_unicode_list_83,
        .list_length    = 1,
        .type           = 1,
    },
    {
        .range_start    = 0,
        .range_length   = 0,
        .glyph_id_start = 84,
        .unicode_list   = eui_test_font_unicode_list_84,
        .list_length    = 1,
        .type           = 1,
    },
    {
        .range_start    = 0,
        .range_length   = 0,
        .glyph_id_start = 85,
        .unicode_list   = eui_test_font_unicode_list_85,
        .list_length    = 1,
        .type           = 1,
    },
    {
        .range_start    = 0,
        .range_length   = 0,
        .glyph_id_start = 86,
        .unicode_list   = eui_test_font_unicode_list_86,
        .list_length    = 1,
        .type           = 1,
    },
};

const Font eui_test_font = {
    .bitmap      = eui_test_font_bitmap,
    .glyphs      = eui_test_font_glyphs,
    .cmaps       = eui_test_font_cmaps,
    .cmap_num    = 28,
    .line_height = 12,
    .base_line   = 8,
};
