//
//  Font header: eui_test_font
//  Auto-generated by ESGUI Font Generator v1.0.0
//

#ifndef eui_test_font_H
#define eui_test_font_H

#include <stdint.h>
#include "ESGUI_BSP_Text.h"

extern const Font eui_test_font;

#endif /* eui_test_font_H */
